import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import { Layout } from "@/components/Layout/Layout";
import Providers from "@/utils/Providers/Providers";

const manrope = Manrope({
  weight: ["300", "400", "500", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <Providers>
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  );
}
